# Setup
title:               Data Empowerment
tagline:             ''
description:         Data Empowerment Projects
url:                 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Victor Jin
  url:               'https://Viktorjin.github.io/'
  email:             jinyushanvictor@outlook.com
  baseurl:           ''


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
